# INTRODUCTION

The Basin and Coastal Scale Interactions Program of Fisheries and Oceans conducted an ecosystem-based survey, targeting juvenile Pacific salmon (*Oncorhynchus* spp.) from `r surveyDateRange` on the `r vessel`. The main objectives of this surveys were:

1. to determine the abundance, condition, distribution, and genetic stock composition of juvenile salmon present from Queen Charlotte Strait to Dixon Entrance in the fall, and 

2. to optimize the new LFS 1142 (offshore) net deployment and new oceanographic sampling protocols for the [2022 Pan-Pacific High Seas Expedition](https://yearofthesalmon.org/high-seas-expeditions/) on the `r vessel`. 

This survey supports research into linkages between oceanographic conditions, fish abundance and community composition, Pacific Salmon ocean ecology and forecasting adult returns. Survey data will also be presented at and integrated into the 2020 [State of the Pacific Ocean](https://dfo-mpo.gc.ca/oceans/publications/index-eng.html#soto-pac-tech). This preliminary data report documents the biological, oceanographic, and plankton data collected during the `r surveyName` from `r surveyDateRange`.  