# MATERIALS AND METHODS

## SURVEY LOCATIONS

Fishing (Figure \@ref(fig:mapfish)), oceanographic (Figure \@ref(fig:mapctd)) and zooplankton sampling (Figure \@ref(fig:mapplankton)) occurred west of Triangle Island and in Queen Charlotte Sound, Hecate Strait, and Dixon Entrance. 

## FISHING OPERATIONS

The vessel deployed two mid water trawl nets: the offshore LFS 1142 trawl net and coastal LFS 7742 trawl net (Appendix \@ref(app:appNet), manufactured by [LFS Trawl](https://www.lfsinc.com/commericalfishinggear/trawl.htm) (LFS Net Systems, Bellingham, USA). Both trawl nets are two-bridle mid water nets, and have codend liners to retain smaller species (offshore LFS 1142 codend liner is 4 mm and coastal LFS 7742 codend liner is 6.35 mm). The offshore LFS 1142 trawl net was designed for [High Seas Expeditions](https://yearofthesalmon.org/high-seas-expeditions/), and has never been deployed from the *`r vessel`*. Equipment set up was incorporated into this survey because gear testing was cancelled due to COVID-19 restrictions. The codend was left open for the offshore LFS 1142 trawl net gear optimization. The main difference between the offshore LFS 1142 trawl net and coastal LFS 7742 trawl net is that the offshore LFS 1142 trawl net was designed to have a larger net opening. The offshore LFS 1142 trawl net opening was designed to be 46 m wide by 30 m high [@somov2020], or an area of 1380 m^2^. The coastal LFS 7742 trawl net was designed to have a net opening of 30 m wide by 15 m high, or an area of 450 m^2^ (Figure \@ref(fig:coastalnet)). Actual net openings varied; therefore, height and width dimensions were recorded for each tow and used in the calculation of catch per swept volume (Appendix \@ref(app:appBridge)). 

Two chain clumps were attached to the footrope with approximately 340 kg (750 lbs) and 204 kg (450 lbs) per chain clump for the offshore LFS 1142 trawl net and coastal LFS 7742 trawl net respectively. [Thyborøn](https://thyboron-trawldoor.dk/) Type 15 VF, 4.5 m^2^ mid water doors (730 kg each) with [Scanmar](https://www.scanmar.no/) SS4 door sensors, were used with both nets. A [Simrad](https://www.kongsberg.com/maritime/) FS70 was used as a third wire trawl sonar to the monitor net opening in real time, and [Scanmar](https://www.scanmar.no/) SS4 clump sensors were attached near the wing tips. In addition, [RBR duet^3^ temperature and depth sensors](https://rbr-global.com/products/compact-loggers/rbrduet-td) (RBR Ltd., Ottawa, ON, Canada) were attached to the headrope and footrope to record depth every 30 seconds. The vertical net opening was plotted over time to show the net opening and depth in order to improve consistency between tows.

Tow speed varied between 6.1 to 9.6 km/hour (3.3 and 5.2 knots) speed over ground, depending on the wind, tide, and current, in order to reach the target headrope depth. The target headrope depths were 0 m (surface) and 15 m (depth). Two A-6 floats 86.4 cm x 118.1 cm (34" x 46.5") were attached to sixth blue knot on headrope for surface tows. Warp length ranged from 190-200 m for surface tows, and 227 to 243 m for 15 m headrope depth tows. Target tow duration was 15-20 min once the trawls doors were locked and the net fishing.

## BIOLOGICAL SAMPLES
All shark species were released alive after identification and length measurements. The remaining species were sorted by species or taxonomic group, then the individuals measured for length and weight. Stomachs were analysed at sea following an established protocol [@king2018]. For each species in the tow, up to five whole bodies and five muscle tissues were collected for energy density and stable isotope analyses. Additional collection for Pacific Salmon species included: fin clips for genetic stock identification, otoliths, and adipose fin status, and coded wire tags (CWTs).

## OCEANOGRAPHY

A 24 bottle rosette with [Sea-bird](https://www.seabird.com/) 911 CTD (Sea-bird Electronics Bellevue Washington, USA), was deployed to 10 m above bottom for the first two stations. The Niskin bottles were sampled for nutrients, chlorophyll a, and trace metals using ligand analysis. Unfortunately, the cable on the Launch and Recovery System (LARS) failed on the third CTD rosette deployment so a standalone Sea-bird 25 CTD was used for water profiles thereafter. Surface water was collected for chlorophyll and nutrient analyses for the remainder of the survey. Seawater samples for nitrate, phosphate, and silicate were placed in acid-washed glass test tubes and frozen. Seawater for chlorophyll a (chl a) estimation were filtered with GF/F glass fibre filter disks. Filter disks were then placed in polypropylene scintillation vials and frozen. Both the chlorophyll and nutrient samples were frozen and maintained at -80&deg;C. Seawater and chl a samples were sent for analyses at Fisheries and Oceans Canada Institute of Ocean Sciences, Sidney, BC. 

## ZOOPLANKTON AND NEKTON SAMPLING

At zooplankton stations (Figure \@ref(fig:mapplankton)), vertical tows were conducted to approximately 250 m or within 10 m of the bottom with two 60 cm diameter, 253 micrometer mesh nets mounted in a bongo-drum style frame. Zooplankton collected from the flow meter side were preserved in 10% formalin and sent to the zooplankton laboratory at the Institute of Ocean Sciences (Sidney, BC) for species classification and enumeration. The remaining zooplankton sample was sorted into four size fractions by successively sieving through 8.0, 1.7, 1.0, and 0.25 mm screens. Individual size fractions were frozen for future stable isotope, energy density, and proximate analyses. 

Two additional oblique bongo tows were completed at the offshore stations (CS01, T01). The vessel speed was controlled to allow a 45 degree wire angle to increase the volume of water sampled. Oblique zooplankton tows are a method under consideration for the 2022 Pan-Pacific High Seas Expedition.

The MOCNESS nekton sampling gear was deployed at three stations (CS01, MT08, Mason53) from the starboard side of the vessel. The vessel speed was controlled to allow a 45 degree angle on the wire. A net was open during descent to 300-500 m, depending on the starting bottom depth. Five additional strata were sampled during ascent, with the depth strata depending on the maximum depth and acoustic signals.
