# DISCUSSION

This ecosystem-based juvenile Pacific Salmon survey collected valuable information on distribution, abundance, condition, and genetic stock composition (GSI) for juvenile Pacific Salmon in the north coast of British Columbia. Overall, juvenile Chum Salmon and Pink Salmon were most abundant, whereas Chinook Salmon were least abundant. Distributions and stomach contents varied by species. We collected physical oceanographic water profiles, and zooplankton abundance and composition associated with the Pacific Salmon caught. As it becomes available, the data from laboratory analysis (i.e. GSI, energy density, zooplankton composition) will be integrated into the survey data. These catch data, along with condition and GSI data, supplement historic juvenile Pacific Salmon surveys in these areas and will be reported in Fisheries and Oceans Canada [State of the Pacific Ocean](https://dfo-mpo.gc.ca/oceans/publications/index-eng.html#soto-pac-tech) report and the annual Fraser River Sockeye Forecasting Supplement [@macdonald2020]. 

The offshore LFS 1142 trawl net was deployed for the first time on the *`r vessel`* with success. The setup and deployment procedure for this gear can be applied to the [Pan-Pacific High Seas Expedition](https://yearofthesalmon.org/high-seas-expeditions/). Three MOCNESS and two oblique bongo tows were successfully conducted off the starboard in calm waters. The LARS was successfully used deploy the CTD rosette at two stations.  
