---
title: "Ecosystem-Based Juvenile Salmon (*Oncorhynchus* spp.) Survey in Northern British Columbia, October 6-16, 2020"
year: 20XX
report_number: nnn
author: |
  Erika Anderson^1^,
  Jackie King^1^, and
  Tyler Zubkowski^1^
author_list: "Anderson, E., King, J. and Zubkowski, T."
region: Pacific Region
isbn: ""
address: |
  ^1^Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
phone: "(250) 756-7067"
author_footnote: "Email: Erika.Anderson@dfo-mpo.gc.ca | telephone: (250) 756-7067"
abstract: |
  Fisheries and Oceans Canada conducted an ecosystem-based survey from October 6-16, 2020 on the CCGS Sir John Franklin targeting juvenile salmon from Queen Charlotte Sound to Dixon Entrance. The survey was designed to determine the distribution, abundance, and ecology of juvenile Pacific salmon (Oncorhynchus sp.) in northern British Columbia during the fall season. In addition, gear optimization occurred for the International Year of the Salmon Survey.
    
abstract_other: |
  Voici le résumé. 
output:
 csasdown::techreport_word:
   french: false
   copy_sty: false
   line_nums: false
   line_nums_mod: 1
type:
  techreport
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
lot: true
lof: true
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  cache = FALSE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)

# EA added the options below

# hide NAs within tables
  options(knitr.kable.NA = '')

# turn off significant figures
  options(scipen = 999)
  

```

```{r load-libraries, cache=FALSE}

# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if(length(grep("pdf", names(meta)))){
  french <- meta$`csasdown::techreport_pdf`$french
  prepub <- meta$`csasdown::techreport_pdf`$prepub
}else if(length(grep("word", names(meta)))){
  french <- meta$`csasdown::techreport_word`$french
  prepub <- meta$`csasdown::techreport_word`$prepub
}
# if(french){
#   options(OutDec =  ",")
# }

# load R libraries
library(tidyverse) # data manipulations
library(rosettafish) # french-english translation of figures
library(csasdown) # to build report
library(car) # statistics
library(RODBC) # database connection
library(lubridate) # functions with dates
library(cowplot) # multiple plots in one
library(float) # fix the table-page breaks
library(broom) # display linear model on LW graphs easily
library(xfun) # to convert numeric values to text
library(measurements) #to convert lat/lon values
library(openxlsx) # load excel data
library(rgdal) # to load shapefiles
library(naniar) # function replace_with_na
library(kableExtra) # better table layouts
library(geosphere) # distance between lat and long
library(fossil) # calculate heading

```

```{r database, cache = FALSE}

# #*** change this to your local HSSALMON database within the R project
# db <- "data/HSSALMON.accdb" 
# 
# # access IPES database
# myconn <- odbcConnectAccess2007(db)

```


```{r surveyDetails}

# *** survey number 
# note the extra quotes are needed
CRUISEchr <- "'2020017'"
CRUISEnum <- 2020017

# survey name
surveyName <- "ecosystem-based juvenile salmon survey"

# # create string to query db
# tripQuery <- paste0("SELECT CRUISE_INFO.CRUISE, CRUISE_INFO.START_DATE, CRUISE_INFO.END_DATE, CRUISE_INFO.REGIONS_SURVEYED, CRUISE_INFO.VESSEL
# FROM CRUISE_INFO
# WHERE (((CRUISE_INFO.CRUISE)=", CRUISEchr,"))")
# 
# # get cruise data from database
# tripdf <- sqlQuery(myconn, tripQuery)
# 
# # start date from data
# surveyStartDate <- tripdf$START_DATE
# surveyStart <- as.character(surveyStartDate, format = "%b %d, %Y")
# surveyStartDay <- as.character(surveyStartDate, format = "%B %d")
# 
# # end date from data
# surveyEndDate <- tripdf$END_DATE
# surveyEnd <- as.character(surveyEndDate, format = "%b %d, %Y")
# surveyEndDay <- as.character(surveyEndDate, format = "%d, %Y")
# 
# # date range to use in text
# surveyDateRange <- str_c(surveyStartDay, " to ", surveyEndDay)
# 
# # survey year
# surveyYear <- as.character(year(surveyStartDate))
# 
# # vessel name as variable
# vessel <- str_replace(str_to_title(as.character(tripdf$VESSEL)), "Ccgs", "CCGS")

# maunally add variables
surveyDateRange <- "October 6 to 16, 2020"
surveyYear <- "2020"
vessel <- "CCGS Sir John Franklin"

```

```{r locations}

# load location data for maps from at sea bridge data
# events_orig <- openxlsx::read.xlsx("data/2020-017_BridgeLog_digital_2020-11-18.xlsx",
#                                    sheet = "Details")

events_orig <- readr::read_csv("data/csv/2020-017_BridgeLog_digital_2020-11-30.csv",
                                col_types = cols(
                                  Cruise = col_character(),
                                  Event = col_double(),
                                  Year = col_double(),
                                  Month = col_double(),
                                  Day = col_double(),
                                  StationID = col_character(),
                                  Type = col_character(),
                                  Location = col_character(),
                                  StartTime = col_character(), # excel R conflict for time format
                                  Start_Lat_Deg = col_double(),
                                  Start_Lat_Min = col_double(),
                                  Start_Lat_DD = col_double(),
                                  Start_Long_Deg = col_double(),
                                  Start_Long_Min = col_double(),
                                  Start_Long_DD = col_double(),
                                  Start_Bot_Depth = col_double(),
                                  StopTime = col_character(), # excel R conflict for time format
                                  TowTime = col_character(),
                                  End_Lat_Deg = col_double(),
                                  End_Lat_Min = col_double(),
                                  End_Lat_DD = col_double(),
                                  End_Long_Deg = col_double(),
                                  End_Long_Min = col_double(),
                                  End_Long_DD = col_double(),
                                  StopBotDepth = col_double(),
                                  Warp = col_double(),
                                  Speed = col_double(),
                                  VerticalNetOpening = col_double(),
                                  Doorspread = col_double(),
                                  Wingspread = col_double(),
                                  TargetHeadDepth = col_double(),
                                  ActualHeadDepth = col_double(),
                                  `Chain Clumps` = col_character(),
                                  Comments = col_character()
                                )) 

# wrangle data
events <- events_orig %>%
  filter(!(is.na(Type))) %>%
  mutate(Start_Long_DD = -1* Start_Long_DD,
         End_Long_DD = -1* End_Long_DD)

# find min and max lat and longs for limits to basemap
minLat <- min(events$Start_Lat_DD) + 1 # adjusted for test sets pulling it south
maxLat <- max(events$Start_Lat_DD) 
minLon <- min(events$Start_Long_DD) - 0.5 # adjusted so HG not cut off
maxLon <- max(events$Start_Long_DD)

# load basemap from coastal shapefile
coast <- readOGR("data/Spatial/Land.shp", verbose = FALSE)

# basemap
  basemap <- ggplot() +
    geom_path(data = coast, aes(x = long, y = lat, group = group)) +
    coord_equal() +
    xlim(minLon, maxLon) +
    ylim(minLat, maxLat) +
    labs(x = "Longitude",
         y = "Laititude") +
    # # add scale bar using https://stevemorse.org/nearest/distance.php
    # geom_segment(aes(x = -127.7, y = 48.5, xend = -127.56375, yend = 48.5), size = 2) +
    # geom_segment(aes(x = -127.56375, y = 48.5, xend = -127.4275, yend = 48.5), size = 2, color = "grey") +
    # geom_segment(aes(x = -127.4275, y = 48.5, xend = -127.29125, yend = 48.5), size = 2) +
    # geom_text(aes(-127.5, 48.6), label = "30 km") +
    theme_bw() 


```

```{r net}

net <- events %>%
  mutate(NOPE = str_extract(Comments, "DO NOT USE")) %>%
  filter(is.na(NOPE)) %>%
  filter(Type == "Trawl7742" | Type == "Trawl1142") %>%
  group_by(Type, TargetHeadDepth) %>%
  summarize(Vertavg = mean(VerticalNetOpening),
            Vertmin = min(VerticalNetOpening),
            Vertmax = max(VerticalNetOpening),
            Horavg = mean(Wingspread),
            Hormin = min(Wingspread),
            Hormax = max(Wingspread), .groups = "drop")

```


```{r salmon}

# # create string to query db
# salmonQuery <- paste0("SELECT CRUISE_INFO.CRUISE, BRIDGE.EVENT, BRIDGE.YEAR, BRIDGE.MONTH, BRIDGE.DAY, BRIDGE.DATE, BRIDGE.START_LAT, BRIDGE.START_LONG, BRIDGE.DISTANCE, BRIDGE.NET_OPENING_WIDTH, BRIDGE.NET_OPENING_HEIGHT, BRIDGE.HEAD_DEPTH, BRIDGE.[ESTIMATED_CATCHES_ BY_WT], BRIDGE.PK_JUV, BRIDGE.CM_JUV, BRIDGE.CM_ADULT, BRIDGE.SE_JUV, BRIDGE.CO_JUV, BRIDGE.CK_JUV, BRIDGE.GEAR_TYPE, BRIDGE.COMMENTS
# FROM (CRUISE_INFO INNER JOIN STATION_INFO ON CRUISE_INFO.CRUISE = STATION_INFO.CRUISE) INNER JOIN BRIDGE ON STATION_INFO.STATION_ID = BRIDGE.STATION_ID
# WHERE (((CRUISE_INFO.CRUISE)=", CRUISEchr,"))")
# 
# # get cruise data from database
# salmondf_orig <- sqlQuery(myconn, salmonQuery)
salmondf_orig <- readr::read_csv("data/csv/salmondf.csv",
                                 col_types = cols(
  CRUISE = col_double(),
  EVENT = col_double(),
  Year = col_double(),
  Month = col_character(),
  Day = col_double(),
  Date = col_character(), # MS Access and R date format conflict
  START_LAT = col_double(),
  START_LONG = col_double(),
  DISTANCE = col_double(),
  NET_OPENING_WIDTH = col_double(),
  NET_OPENING_HEIGHT = col_double(),
  HEAD_DEPTH = col_double(),
  `ESTIMATED_CATCHES_ BY_WT` = col_character(),
  PK_JUV = col_double(),
  CM_JUV = col_double(),
  CM_ADULT = col_double(),
  SE_JUV = col_double(),
  CO_JUV = col_double(),
  CK_JUV = col_double(),
  GEAR_TYPE = col_character(),
  COMMENTS = col_character()
))

# wrangle data for volume swept CPUE
salmondf <- salmondf_orig %>%
  mutate(NOPE = str_extract(COMMENTS, "DO NOT USE")) %>%
  filter(is.na(NOPE)) %>%
  mutate(DISTANCE_KM = DISTANCE * 1.852,
         WIDTH_KM = NET_OPENING_WIDTH/1000,
         HEIGHT_KM = NET_OPENING_HEIGHT/1000,
         MOUTH_KM2 = WIDTH_KM * HEIGHT_KM,
         VOLUME_KM3 = MOUTH_KM2 * DISTANCE_KM,
         PK_JUV_KM3 = PK_JUV/VOLUME_KM3,
         CM_JUV_KM3 = CM_JUV/VOLUME_KM3,
         SE_JUV_KM3 = SE_JUV/VOLUME_KM3,
         CO_JUV_KM3 = CO_JUV/VOLUME_KM3,
         CK_JUV_KM3 = CK_JUV/VOLUME_KM3)



```

```{r lengths}

# # create string to query db
# lengthQuery <- paste0("SELECT CRUISE_INFO.CRUISE, BIOLOGICAL.FISH_NUMBER, BIOLOGICAL.DATE_CAPTURED, BIOLOGICAL.SPECIES, BIOLOGICAL.SHIP_FL, BIOLOGICAL.SHIP_SL, BIOLOGICAL.SHIP_TL, BIOLOGICAL.SHIP_ML, BIOLOGICAL.SHIP_BD, BIOLOGICAL.SHIP_WT
# FROM (CRUISE_INFO INNER JOIN STATION_INFO ON CRUISE_INFO.CRUISE = STATION_INFO.CRUISE) INNER JOIN (BIOLOGICAL_JUNCTION INNER JOIN BIOLOGICAL ON BIOLOGICAL_JUNCTION.FISH_NUMBER = BIOLOGICAL.FISH_NUMBER) ON STATION_INFO.STATION_ID = BIOLOGICAL_JUNCTION.STATION_ID
# WHERE (((CRUISE_INFO.CRUISE)=", CRUISEchr,"))")
# 
# # get cruise data from database
# lengthFreq_orig <- sqlQuery(myconn, lengthQuery)
lengthFreq_orig <- readr::read_csv("data/csv/lengthFreq.csv",
                                   col_types = cols(
  CRUISE = col_double(),
  FISH_NUMBER = col_character(),
  DATE_CAPTURED = col_character(), # Access and R date format conflict
  SPECIES = col_character(),
  SHIP_FL = col_double(),
  SHIP_SL = col_double(),
  SHIP_TL = col_double(),
  SHIP_ML = col_double(),
  SHIP_BD = col_double(),
  SHIP_WT = col_double()
))

# wrangle data
lengthFreq <- lengthFreq_orig %>%
  pivot_longer(., cols = c("SHIP_FL", "SHIP_SL", "SHIP_TL", "SHIP_ML", "SHIP_BD"),
               names_to = "LengthType",
               values_to = "LENGTH") %>%
  mutate( LOG.LEN = log(LENGTH),
         LOG.WT = log(SHIP_WT)) %>%
  rename(TRIP_ID = CRUISE,
         WEIGHT = SHIP_WT,
         COMMON_NAME = SPECIES)

```

```{r catch}

# # create string to query db
# # omit unusable tow in QCST01
# catchQuery <- paste0("SELECT STATION_INFO.CRUISE, BCSI_ECOSYSTEM_SPECIES_TOTALS.STATION_ID, BCSI_ECOSYSTEM_SPECIES_TOTALS.SPECIES_CODE, BCSI_ECOSYSTEM_SPECIES_TOTALS.SPECIES_COMMON_NAME, BCSI_ECOSYSTEM_SPECIES_TOTALS.PIECES, BCSI_ECOSYSTEM_SPECIES_TOTALS.WT
# FROM (STATION_INFO INNER JOIN BCSI_ECOSYSTEM_SPECIES_TOTALS ON STATION_INFO.STATION_ID = BCSI_ECOSYSTEM_SPECIES_TOTALS.STATION_ID) INNER JOIN BRIDGE ON (BCSI_ECOSYSTEM_SPECIES_TOTALS.STATION_ID = BRIDGE.STATION_ID) AND (STATION_INFO.STATION_ID = BRIDGE.STATION_ID)
# WHERE (((STATION_INFO.CRUISE)=", CRUISEchr,"))")
# 
# # get cruise data from database
# catch_orig <- sqlQuery(myconn, catchQuery)
catch_orig <- readr::read_csv("data/csv/catch_orig.csv",
                              col_types = cols(
  CRUISE = col_double(),
  STATION_ID = col_character(),
  SPECIES_CODE = col_character(),
  SPECIES_COMMON_NAME = col_character(),
  PIECES = col_double(),
  WT = col_double()
))

# upload GFBIO species table for common and scientific names
species_orig <- read_csv("data/csv/C_Species.csv",
                         col_types = cols(
  SPECIES_CODE = col_character(),
  SPECIES_DESC = col_character(),
  ROW_VERSION = col_double(),
  SPECIES_COMMON_NAME = col_character(),
  SPECIES_SCIENCE_NAME = col_character(),
  ITIS_TSN = col_double(),
  TAXONOMIC_RANK = col_character(),
  RSTY_ID = col_double(),
  PARENT_RSTY_ID = col_double(),
  PARENT_TAXONOMIC_UNIT = col_character(),
  SPECIES_GROUPING = col_character(),
  LSID = col_character()
))

# simiplify species table
species <- species_orig %>%
  select(SPECIES_CODE, SPECIES_COMMON_NAME, SPECIES_SCIENCE_NAME)

# wrangle data
catch <- catch_orig %>%
  # omit unusable tow in QCST01
  filter(STATION_ID != "BCSI-2020017-QCST01") %>%
  
# fix species codes where R dropped the 0 preceeding the code
  mutate(SPECIES_CODE = if_else(SPECIES_CODE != "96", as.character(SPECIES_CODE), "096"),
         SPECIES_CODE = if_else(SPECIES_CODE != "41", as.character(SPECIES_CODE), "041")) %>%
  left_join(., species, by = "SPECIES_CODE") %>%
  mutate(DISPLAY_COMMON = if_else(is.na(SPECIES_COMMON_NAME.y), as.character(SPECIES_COMMON_NAME.x), SPECIES_COMMON_NAME.y)) %>%
  mutate(DISPLAY_COMMON = str_remove_all(DISPLAY_COMMON, "[()](JUVENILES)[)]*"),
         DISPLAY_COMMON = str_remove(DISPLAY_COMMON, "[()](ADULTS)[)]*")) %>%
    mutate(COMMON_NAME = paste0(str_sub(DISPLAY_COMMON, 1,1), str_sub(tolower(DISPLAY_COMMON),2)),
         SCIENTIFIC_NAME = paste0(str_sub(SPECIES_SCIENCE_NAME, 1,1), str_sub(tolower(SPECIES_SCIENCE_NAME),2))) %>%
  group_by(COMMON_NAME, SCIENTIFIC_NAME) %>%
  summarise(numTows = n(),
            totalWgt = sum(WT, na.rm = TRUE),
            maxWgt = max(WT, na.rm = TRUE),
            meanWgt = round(mean(WT, na.rm = TRUE), 0)) %>%
  ungroup() %>%
  arrange(desc(totalWgt), desc(numTows)) %>%
  naniar::replace_with_na(replace = list(meanWgt = NaN, 
                                         maxWgt = -Inf, 
                                         totalWgt = 0)) 
  
```

```{r lengthweight}

lw_length <- lengthFreq %>%
  filter(!(is.na(LENGTH))) %>%
  separate(., FISH_NUMBER, into = c("Program", "Survey", "Station", "SPECIES_CODE", "FishNum")) %>%
  group_by(COMMON_NAME) %>%
  mutate(numTows = length(unique(Station))) %>%
  summarize(numTows = mean(numTows),            
            lengthNum = sum(!is.na(LENGTH)),
            meanLen = round(mean(LENGTH, na.rm = TRUE), 0),
            minLen = min(LENGTH, na.rm = TRUE),
            maxLen = max(LENGTH, na.rm = TRUE),
            .groups = "drop")

lw_weight <- lengthFreq %>%
  filter(!(is.na(LENGTH))) %>%
  filter(!(is.na(WEIGHT))) %>%
  group_by(COMMON_NAME) %>%
  summarize(wgtNum = sum(!is.na(WEIGHT)),
            meanWGT = round(mean(WEIGHT, na.rm = TRUE), 0),
            minWgt = min(WEIGHT, na.rm = TRUE),
            maxWgt = max(WEIGHT, na.rm = TRUE),
            .groups = "drop")

# join tables
lw <- lw_length %>%
  full_join(., lw_weight, by = "COMMON_NAME") %>%
  mutate(COMMON_NAME = paste0(str_sub(COMMON_NAME, 1,1), str_sub(tolower(COMMON_NAME),2)),
         COMMON_NAME = case_when(
           COMMON_NAME == "Opalescent squid" ~ "Opalescent inshore squid", 
           COMMON_NAME == "Chinook" ~ "Chinook salmon",
           COMMON_NAME == "Pink" ~ "Pink salmon",
           COMMON_NAME == "Sockeye" ~ "Sockeye salmon",
           COMMON_NAME == "Coho" ~ "Coho salmon",
           COMMON_NAME == "Chum" ~ "Chum salmon",
           COMMON_NAME == "Herring" ~ "Pacific Herring",
           COMMON_NAME == "Aequorea" ~ "Water Jelly",
           COMMON_NAME == "Rock sole" ~ "Flatfish",
           TRUE ~ COMMON_NAME)
         ) %>%
  arrange(-lengthNum)

```

```{r stomach}

# # sql in HSSALMON
# SELECT STATION_INFO.CRUISE, BIOLOGICAL.SPECIES, BCSI_STOMACH_CONTENTS.*
# FROM STATION_INFO INNER JOIN ((BIOLOGICAL_JUNCTION INNER JOIN BCSI_STOMACH_CONTENTS ON BIOLOGICAL_JUNCTION.FISH_NUMBER = BCSI_STOMACH_CONTENTS.FISH_NUMBER) INNER JOIN BIOLOGICAL ON BIOLOGICAL_JUNCTION.FISH_NUMBER = BIOLOGICAL.FISH_NUMBER) ON STATION_INFO.STATION_ID = BIOLOGICAL_JUNCTION.STATION_ID
# WHERE (((STATION_INFO.CRUISE)="2020017"));

# read csv 
stomachdf_orig <- readr::read_csv("data/csv/stomachdf.csv",
                             col_types = cols(
  CRUISE = col_double(),
  SPECIES = col_character(),
  FISH_NUMBER = col_character(),
  `1-PREY_CODE` = col_character(),
  `1-VOLUME` = col_double(),
  `1-DIGESTION` = col_double(),
  `1-PREY_TRACES` = col_character(),
  `2-PREY_CODE` = col_character(),
  `2-VOLUME` = col_double(),
  `2-DIGESTON` = col_double(),
  `2-PREY_TRACES` = col_character(),
  `3-PREY_CODE` = col_character(),
  `3-VOLUME` = col_double(),
  `3-DIGESTION` = col_double(),
  `3-PREY_TRACES` = col_character(),
  COMMENTS = col_character()
))


# wrangle data
stomachTows <- stomachdf_orig %>%
  separate(., FISH_NUMBER, into = c("Program", "Survey", "Station", "SPECIES_CODE", "FishNum")) %>%
  group_by(SPECIES) %>%
  summarise(NumTows = length(unique(Station)))

stomachdf <- stomachdf_orig %>%
  group_by(SPECIES) %>%
  summarise(NumStomachs = length(`1-PREY_CODE`),
            NumEmpty = sum(`1-PREY_CODE` == "M002"),
            .groups = "drop") %>%
  mutate(PerEmpty = round((NumEmpty/NumStomachs)*100),0) %>%
  left_join(., stomachTows, by = "SPECIES")  %>%
  arrange(-NumTows) %>%
  mutate(COMMON_NAME = paste0(str_sub(SPECIES, 1,1), str_sub(tolower(SPECIES),2)),
         COMMON_NAME = case_when(
           COMMON_NAME == "Opalescent squid" ~ "Opalescent inshore squid", 
           COMMON_NAME == "Chinook" ~ "Chinook salmon",
           COMMON_NAME == "Pink" ~ "Pink salmon",
           COMMON_NAME == "Sockeye" ~ "Sockeye salmon",
           COMMON_NAME == "Coho" ~ "Coho salmon",
           COMMON_NAME == "Chum" ~ "Chum salmon",
           COMMON_NAME == "Herring" ~ "Pacific Herring",
           COMMON_NAME == "Aequorea" ~ "Water Jelly",
           COMMON_NAME == "Rock sole" ~ "Flatfish",
           TRUE ~ COMMON_NAME)) %>%
  select(COMMON_NAME, NumTows, NumStomachs, NumEmpty, PerEmpty)

```

```{r prey}

# wrangle stomach data
preycode <- stomachdf_orig %>%
  select(FISH_NUMBER, `1-PREY_CODE`, `2-PREY_CODE`, `3-PREY_CODE`) %>%
    pivot_longer(., cols = c("1-PREY_CODE", "2-PREY_CODE", "3-PREY_CODE"),
                 values_drop_na = TRUE, names_to = "PreyLevel", values_to = "PreySpecies") %>%
  mutate(Level = str_extract_all(PreyLevel, "[0-3]"),
         # this is a typo and should be fixed in database, should be 0A0 not letters OAO
         #PreySpecies = if_else(PreySpecies == "OAO", "0A0", PreySpecies) 
  )
  

volume <- stomachdf_orig %>%
  select(FISH_NUMBER, `1-VOLUME`, `2-VOLUME`, `3-VOLUME`) %>%
    pivot_longer(., cols = c("1-VOLUME", "2-VOLUME", "3-VOLUME"),
                 values_drop_na = TRUE, names_to = "VolLevel", values_to = "PreyVolume") %>%
  mutate(Level = str_extract_all(VolLevel, "[0-3]"))

# join together
prey <- preycode %>%
  full_join(., volume, by = c("FISH_NUMBER", "Level")) %>%
  filter(PreySpecies != "M002") %>%
  mutate(PreySpecies = if_else(PreySpecies == "96", "096", PreySpecies)) %>%
  separate(., FISH_NUMBER, into = c("Program", "Survey", "Station", "SPECIES_CODE", "FishNum")) %>%
  group_by(SPECIES_CODE, PreySpecies) %>%
  summarise(AvgVolume = round(mean(PreyVolume, na.rm = TRUE),2),
            NumPrey = length(PreyVolume),
            .groups = "drop") %>%
  left_join(., species, by = "SPECIES_CODE") %>%
  mutate(DISPLAY_COMMON = str_remove_all(SPECIES_COMMON_NAME, "[()](JUVENILES)[)]*"),
         #DISPLAY_COMMON = str_remove(DISPLAY_COMMON, "[()](ADULTS)[)]*")
         ) %>%
  mutate(COMMON_NAME = paste0(str_sub(DISPLAY_COMMON, 1,1), str_sub(tolower(DISPLAY_COMMON),2))) %>%
  select(COMMON_NAME, PreySpecies, AvgVolume, NumPrey) %>%
  left_join(., species, by = c("PreySpecies" = "SPECIES_CODE")) %>%
  mutate(PREY_NAME = case_when(
    PreySpecies == "M011" ~ "Unid. Remains",
    PreySpecies == "0A0" ~ "Invertebrate Remains",
    PreySpecies == "M010" ~ "Unid. Fishes",
    PreySpecies == "M014" ~ "Unid. Plankton",
    PreySpecies == "M004" ~ "Misc. Non-marine",
    PreySpecies == "S97" ~ "Flatfish", # this is a typo to fix and should be 597
    TRUE ~ SPECIES_COMMON_NAME)) %>%
  select(COMMON_NAME, PREY_NAME, AvgVolume, NumPrey) %>%
  mutate(PREY_NAME = paste0(str_sub(PREY_NAME, 1,1), str_sub(tolower(PREY_NAME),2))) %>%
  arrange(COMMON_NAME, -AvgVolume)


```

```{r bridge}

# Calculate distance function
calcDist <- function(lat_a, lon_a, lat_b, lon_b) { 
  library(geosphere)
  distm(c(lon_a, lat_a), c(lon_b, lat_b), fun = distGeo) 
} 

bridge <- events %>%
  mutate(Date = lubridate::ymd(str_c(Year, Month, Day, sep = "-"))) %>%
  mutate(# make pretty lat and longs to display
         Start_Lat_Min_NoSec = str_extract_all(Start_Lat_Min, "^[0-9]+"),
         Start_lat_Sec = str_pad(as.character(round(as.numeric(str_extract_all(Start_Lat_Min, "[.][0-9]+$"))*60)), width = 2, side = "left", pad = "0"),
         START_LAT = str_c(Start_Lat_Deg, "\u00B0", Start_Lat_Min_NoSec, "'", Start_lat_Sec),
         
         Start_Long_Min_NoSec = str_extract_all(Start_Long_Min, "^[0-9]+"),
         Start_long_Sec = str_pad(as.character(round(as.numeric(str_extract_all(Start_Long_Min, "[.][0-9]+$"))*60)), width = 2, side = "left", pad = "0"),
         START_LONG = str_c(Start_Long_Deg, "\u00B0", Start_Long_Min_NoSec, "'", Start_long_Sec),
         
         End_Lat_Min_NoSec = str_extract_all(End_Lat_Min, "^[0-9]+"),
         End_lat_Sec = str_pad(as.character(round(as.numeric(str_extract_all(End_Lat_Min, "[.][0-9]+$"))*60)), width = 2, side = "left", pad = "0"),
         END_LAT = str_c(End_Lat_Deg, "\u00B0", End_Lat_Min_NoSec, "'", End_lat_Sec),
         
         End_Long_Min_NoSec = str_extract_all(End_Long_Min, "^[0-9]+"),
         End_long_Sec = str_pad(as.character(round(as.numeric(str_extract_all(End_Long_Min, "[.][0-9]+$"))*60)), width = 2, side = "left", pad = "0"),
         END_LONG = str_c(End_Long_Deg, "\u00B0", End_Long_Min_NoSec, "'", End_long_Sec)
         ) 

bridgetow <- bridge %>%
  mutate(TrawlNet = str_c("LFS ", str_extract(Type, "[0-9]+")),
         Test = str_extract(Comments, "DO NOT USE"),
         Usable = if_else(is.na(Test), "Y", "N"),
         DURATION = str_extract_all(TowTime, "[0-9]+$"),
         SPEED_KM = round(Speed*1.852,1),
         
         HEADING = round(fossil::earth.bear(Start_Long_DD, Start_Lat_DD, End_Long_DD, End_Lat_DD)),
         DISTANCE_NM = round((mapply(lat_a =  Start_Lat_DD, lon_a = Start_Long_DD, #calc. dist.
                           lat_b = End_Lat_DD, lon_b = End_Long_DD,
                           FUN = calcDist) / 1852),2), #division converts to naut. miles
         DISTANCE_KM = round(((mapply(lat_a =  Start_Lat_DD, lon_a = Start_Long_DD, #calc. dist.
                           lat_b = End_Lat_DD, lon_b = End_Long_DD,
                           FUN = calcDist))/1000),2)) %>%
  filter(!(is.na(TrawlNet))) %>%
select(Event, Date, StationID, TrawlNet, StartTime, DURATION, START_LAT, START_LONG, END_LAT, END_LONG, HEADING, SPEED_KM, DISTANCE_KM, VerticalNetOpening, Wingspread, Warp, Doorspread, TargetHeadDepth, ActualHeadDepth, Start_Bot_Depth, StopBotDepth, Usable) %>%
    dplyr::rename(
      "Event Number" = Event,
      "Station ID" = StationID,
      "Trawl Net" = TrawlNet,
         "Start Time (PDT)" = StartTime,
         "Duration (min)" = DURATION,
         "Start Latitude" = START_LAT,
         "Start Longitude" = START_LONG,
         "End Latitude" = END_LAT,
         "End Longitude" = END_LONG,
         "Direction of Tow (deg)" = HEADING,
         "Vessel Speed (km/h)" = SPEED_KM,
         "Distance Towed (km)" = DISTANCE_KM,
         "Net Opening Height (m)" = VerticalNetOpening,
         "Net Opening Width (m)" = Wingspread,
         "Warp Length (m)" = Warp,
         "Door Spread (m)" = Doorspread,
         "Target Headrope Depth (m)" = TargetHeadDepth,
         "Average Headrope Depth (m)" = ActualHeadDepth,
         "Start Bottom Depth (m)" = Start_Bot_Depth,
         "End Bottom Depth (m)" = StopBotDepth)


# transpose table into display format
# tows as column names
bridge_t <- as.data.frame(t(bridgetow))

# column names as vector
col_from <- colnames(bridge_t)

# column names from tow number
col_to <- 1:27

# rename column names with consequtive tow number
bridge_t <- bridge_t %>%
  rename_at(vars(col_from), function(x) col_to)

# make vector for row names
MeasurementNames <- as.vector(row.names(bridge_t))
  
# make function to create discrete tables for display
breakBridgeTable <- function(df, rowNum, MeasurementNames) {
  
  df <- bridge_t %>%
    select(rowNum) %>%  
    mutate(`Tow Number` = MeasurementNames) %>%
    select(`Tow Number`, everything())
    
}

# divide the total tows by 3 to make discrete tables
bridge1 <- breakBridgeTable(bridge_t, 1:7, MeasurementNames)
bridge2 <- breakBridgeTable(bridge_t, 8:15, MeasurementNames)
bridge3 <- breakBridgeTable(bridge_t, 16:23, MeasurementNames)
bridge4 <- breakBridgeTable(bridge_t, 24:27, MeasurementNames)

```

```{r CTDdepthtime}

# date, start time, bottom depth, gear depth for CTD, Bongo Vert
# recommend start lat/long and end lat/long also since not always with tow

ocean_orig <- bridge %>%
  filter(!(Type %in% c("Trawl7742", "Trawl1142"))) %>%
  filter(StationID != "Test1") %>%
  select(Event, Date, StationID, Type, StartTime, Start_Bot_Depth, CastDepth)

# only CTD and vertical plankton tows for this table
ocean_wider <- ocean_orig %>%
  select(-Event) %>%
  mutate(Type = if_else(Type == "ROS", "CTD", Type)) %>%
  filter(Type %in% c("BongoVertical", "CTD")) %>%
  pivot_wider(., names_from = "Type", values_from = c("StartTime","Start_Bot_Depth", "CastDepth")) %>%
  select(Date, StationID, StartTime_CTD, Start_Bot_Depth_CTD, CastDepth_CTD, 
         StartTime_BongoVertical, Start_Bot_Depth_BongoVertical, CastDepth_BongoVertical)

# Bongo Oblique and MOCNESS describe in text and figures only?

```

```{r catchAppendix}

# find event numbers to join by station
stations <- events %>%
  mutate(STATION_ID = str_c("BCSI-2020017-", StationID),
         Test = str_extract(Comments, "DO NOT USE")) %>%
  filter(is.na(Test)) %>%
  filter(Type %in% c("Trawl7742", "Trawl1142")) %>%
  select(Event, STATION_ID, Type)

# wrangle data
catchApp <- catch_orig %>%
  # omit unusable tow in QCST01
  filter(STATION_ID != "BCSI-2020017-QCST01") %>% # remove aborted tow
  
# fix species codes where R dropped the 0 preceeding the code
  mutate(SPECIES_CODE = if_else(SPECIES_CODE != "96", as.character(SPECIES_CODE), "096"),
         SPECIES_CODE = if_else(SPECIES_CODE != "41", as.character(SPECIES_CODE), "041")) %>%
  left_join(., species, by = "SPECIES_CODE") %>%
  mutate(DISPLAY_COMMON = if_else(is.na(SPECIES_COMMON_NAME.y), as.character(SPECIES_COMMON_NAME.x), SPECIES_COMMON_NAME.y)) %>%
  mutate(DISPLAY_COMMON = str_remove_all(DISPLAY_COMMON, "[()](JUVENILES)[)]*"),
         DISPLAY_COMMON = str_remove(DISPLAY_COMMON, "[()](ADULTS)[)]*")) %>%
  mutate(COMMON_NAME = paste0(str_sub(DISPLAY_COMMON, 1,1), str_sub(tolower(DISPLAY_COMMON),2)),
         SCIENTIFIC_NAME = paste0(str_sub(SPECIES_SCIENCE_NAME, 1,1), str_sub(tolower(SPECIES_SCIENCE_NAME),2)),
         WT_KG = round(WT / 1000,2)) %>%
  left_join(., stations, by = "STATION_ID") %>%
  select(COMMON_NAME, Event, WT_KG) %>%
  filter(!(is.na(WT_KG))) %>%
  arrange(Event) %>%
  dplyr::rename(`Event Number` = Event)

catch_spread <- catchApp %>%
  pivot_wider(., names_from = `Event Number`, values_from = WT_KG) %>%
  arrange(COMMON_NAME)

# make vector for species names
speciesNames <- as.vector(catch_spread$COMMON_NAME)

# make function to create discrete tables for displaying catch
# and summary total to bottom row
breakcatchTable <- function(colNum, speciesNames, catch_spread) {
  
  df <- catch_spread %>%
  select(-COMMON_NAME) %>%
    select(colNum) %>%
    mutate(`Event Number` = str_to_title(as.character(speciesNames))) %>%
    select(`Event Number`, everything())
  
  # create summary totals
summaryfunc <- function(z) if (is.numeric(z)) sum(z, na.rm = TRUE) else ''
sumrow <- as.data.frame(lapply(df, summaryfunc))
sumrow$Event.Number <- as.character(sumrow$Event.Number)
sumrow[1,1] <- "TOTAL" # *** need to add if else to leave unusable tows as - here

# create vector of column names to match
colNamesdf <- colnames(df)
colnames(sumrow) <- colNamesdf

df <- rbind(df, sumrow)
}

# these column numbers need to be modified in appendix catchTable section if they change
catch1 <- breakcatchTable(1:11, speciesNames, catch_spread)
catch2 <- breakcatchTable(12:22, speciesNames, catch_spread)

```

